
- name: add add-apt-repostory
  apt: pkg=software-properties-common state=present update_cache=yes
  sudo: yes

- name: add webupd8 ppa
  apt_repository: repo='ppa:webupd8team/java'

# - name: update
#   apt: apt-get update
#   sudo: yes

- name: auto accept oracle jdk license
  shell: echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
  sudo: yes

- name: install java7
  apt: pkg={{item}} state=present update_cache=yes
  with_items:
    - oracle-java7-installer 
    - ca-certificates
  sudo: yes
