---
- hosts: [all]
  sudo: True
  tags: ['system']
  pre_tasks:
    - name: Install Common Packages
      apt: "pkg={{ item }} state=present update_cache=yes"
      with_items:
        - git
        - vim
        - htop
        - unzip
    - name: Remove require tty
      lineinfile: regexp="^\s+\w+\s+requiretty" dest=/etc/sudoers state=absent
    - name: Remove require tty - alt
      lineinfile: regexp="requiretty" dest=/etc/sudoers.d/os_defaults state=absent
  roles:
    - {
        role: 'java7',
        tags:['java']
      }
    - {
        role: 'haproxy',
        marathon_hosts: "{{ groups.mesos_masters }}",
        marathon_port: 8080
      }
    - {
        role: 'docker',
        tags:['docker']
      }