---
- hosts: [mesos_masters]
  sudo: True
  roles:
    - {
        role: 'zookeeper',
        zookeeper_hosts: "{{ groups.mesos_masters}}",
        tags:['zookeeper']
      }
    - {
        role: 'mesos',
        mesos_quorum: "{{ groups.mesos_masters|length }}",
        zookeeper_hostnames: "{{ groups.mesos_masters | join(':' + zookeeper_client_port + ',')  }}:{{ zookeeper_client_port  }}",
        mesos_install_mode: 'master',
        mesos_cluster_name: 'mlh_mesos',
        tags: ['mesos', 'platforms']
      }
    - {
        role: 'marathon',
        zookeeper_hostnames: "{{ groups.mesos_masters | join(':' + zookeeper_client_port + ',')  }}:{{ zookeeper_client_port  }}",
        tags:['mesos-tools']
      }

